
name: Deploy to Amazon Lambda and Gateway

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: us-east-1                 

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Generate Lambda Packages
      run: |
        echo "wassah dude"
        ls -la

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: Deploy Infra to AWS
      run: |
        terraform init
        echo about to mv state files
        echo about to plan
        terraform plan
        terraform apply -auto-approve
      working-directory: infra


    
