
name: Deploy to Amazon Lambda Gateway NAT

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: us-east-1                 

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials from OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.DEPLOY_ROLE }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Verify Identity
      run: |
        echo "wassah dude"
        aws sts get-caller-identity

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: Deploy Infra to AWS
      run: |
        terraform init
        echo about to plan
        terraform plan
        terraform apply -auto-approve
      working-directory: infra


    
